Simulation = "BlsCosiProtocol"
Servers = 1
Bf = 1
Rounds = 10
RunWait = "600s"
Suite = "bn256.adapter"

Hosts, NSubtrees, FailingSubleaders, FailingLeafs, MinDelay, MaxDelay
  4,  1, 0,  0, 0.1, 0.1
  4,  1, 0,  1, 0.1, 0.1
  4,  3, 0,  0, 0.1, 0.1
 10,  3, 0,  0, 0.1, 0.1
 10,  3, 2,  0, 0.1, 0.1
 10,  3, 0,  3, 0.1, 0.1
 20,  5, 0,  0, 0.1, 0.1
 20,  5, 1,  5, 0.1, 0.1
