Simulation = "BlsCosiBundleProtocol"
Servers = 8
Bf = 200
Rounds = 1
RunWait = "600s"
Suite = "bn256.adapter"

Hosts, FailingLeaves, MinDelay, MaxDelay, GossipTick, RumorPeers, ShutdownPeers, TreeMode
    4, 0,             0.0,      0.0,      0.1,        2,          2,             1
    4, 1,             0.0,      0.0,      0.1,        2,          2,             1
   10, 0,             0.0,      0.0,      0.1,        2,          2,             1
   10, 1,             0.0,      0.0,      0.1,        2,          2,             1
   10, 3,             0.0,      0.0,      0.1,        2,          2,             1
   20, 0,             0.0,      0.0,      0.1,        2,          2,             1
   20, 5,             0.0,      0.0,      0.1,        2,          2,             1
    4, 0,             0.01,     0.5,      0.1,        2,          2,             1
    4, 1,             0.01,     0.5,      0.1,        2,          2,             1
   10, 0,             0.01,     0.5,      0.1,        2,          2,             1
   10, 1,             0.01,     0.5,      0.1,        2,          2,             1
   10, 3,             0.01,     0.5,      0.1,        2,          2,             1
   20, 0,             0.01,     0.5,      0.1,        2,          2,             1
   20, 5,             0.01,     0.5,      0.1,        2,          2,             1
