Simulation = "BlsCosiBundleProtocol"
Servers = 8
Bf = 200
Rounds = 1
RunWait = "600s"
Suite = "bn256.adapter"

Hosts, FailingLeaves, MinDelay, MaxDelay
    4, 0,             0.0,      0.0
    4, 1,             0.0,      0.0
   10, 0,             0.0,      0.0
   10, 1,             0.0,      0.0
   10, 3,             0.0,      0.0
   20, 0,             0.0,      0.0
   20, 5,             0.0,      0.0
    4, 0,             0.01,     0.5
    4, 1,             0.01,     0.5
   10, 0,             0.01,     0.5
   10, 1,             0.01,     0.5
   10, 3,             0.01,     0.5
   20, 0,             0.01,     0.5
   20, 5,             0.01,     0.5
