Simulation = "BlsCosiBundleProtocol"
Servers = 8
Bf = 200
Rounds = 10
RunWait = "600s"
Suite = "bn256.adapter"

Hosts, FailingLeaves, MinDelay, MaxDelay, GossipTick, RumorPeers, ShutdownPeers, TreeMode
   10, 3,             0.00,     0.0,      0.1,        2,          2,             1
   10, 3,             0.00,     0.0,      0.1,        2,          2,             1
   10, 3,             0.00,     0.0,      0.1,        2,          2,             1
