Simulation = "BlsCosiBundleProtocol"
Servers = 1
Bf = 1
Rounds = 1
RunWait = "600s"
Suite = "bn256.adapter"

Hosts, FailingLeaves, MinDelay, MaxDelay, GossipTick, RumorPeers, ShutdownPeers, TreeMode
   20, 0,             0.40,     0.40,     0.1,        2,          2,             0
   20, 0,             0.40,     0.40,     0.1,        2,          2,             0
   20, 0,             0.40,     0.40,     0.1,        2,          2,             0
   20, 0,             0.40,     0.40,     0.1,        2,          2,             0
   20, 0,             0.40,     0.40,     0.1,        2,          2,             0
   20, 0,             0.40,     0.40,     0.1,        2,          2,             0
   20, 0,             0.40,     0.40,     0.1,        2,          2,             0
   20, 0,             0.40,     0.40,     0.1,        2,          2,             0
   20, 0,             0.40,     0.40,     0.1,        2,          2,             0
   20, 0,             0.40,     0.40,     0.1,        2,          2,             0
